cmake -S . -B build -G "Visual Studio 17 2022" ^
      -DCMAKE_POLICY_VERSION_MINIMUM=3.5 ^
      -DCMAKE_EXPORT_COMPILE_COMMANDS=ON ^
      -DCMAKE_C_COMPILER_LAUNCHER=sccache ^
      -DCMAKE_CXX_COMPILER_LAUNCHER=sccache